name: EV Agents

on:
  schedule:
    - cron: "*/30 * * * *"   # corre de 30 em 30 minutos
  workflow_dispatch: {}       # botão "Run workflow"

permissions:
  contents: write             # permite fazer commit/push

jobs:
  run-agents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # cria ficheiros mínimos se não existirem
      - name: Prepare minimal inputs
        run: |
          mkdir -p data
          [ -f data/matches.csv ] || echo "league,utc_date,home,away,match_id,round" > data/matches.csv
          [ -f data/results.csv ] || echo "league,utc_date,home,away,home_goals,away_goals" > data/results.csv
          [ -f data/segments.csv ] || echo "league,team,bin_start_min,gf_per90_bin,ga_per90_bin" > data/segments.csv
          [ -f data/recent_form.csv ] || echo "league,team,metric,value" > data/recent_form.csv

      - name: Run fetch_odds (The Odds API)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          REGION: ${{ secrets.REGION || 'eu' }}
          MARKETS: ${{ secrets.MARKETS || 'h2h,totals,btts' }}
          ODDS_FORMAT: ${{ secrets.ODDS_FORMAT || 'decimal' }}
          SPORTS: ${{ secrets.SPORTS || 'soccer_epl,soccer_spain_la_liga,soccer_portugal_primeira_liga' }}
        run: |
          python agents/fetch_odds.py

      - name: Build model (Poisson baseline)
        run: |
          python agents/build_model_poisson.py

      - name: Merge & export
        run: |
          python agents/ensemble.py

      - name: Commit CSV outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv || true
          git commit -m "update data $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
